"use client";
import React from "react";
import Head from "next/head";
import { Fade } from "react-awesome-reveal";
import { useTheme } from "next-themes";
import { RiMoonFill, RiSunLine } from "react-icons/ri";

export default function Home() {
  const { theme, setTheme } = useTheme();

  React.useEffect(() => {
    setTheme("light");
  }, []);

  return (
    <>
      <Head>
        <title>Bardle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <div className="fixed right-6 top-6">
            {theme === "dark" ? (
              <Fade triggerOnce direction="down" delay={600}>
                <button
                  onClick={() => setTheme("light")}
                  className="bg-slate-100 p-2 rounded-xl"
                >
                  <RiSunLine size={25} color="black" />
                </button>
              </Fade>
            ) : (
              <Fade triggerOnce direction="down" delay={600}>
                <button
                  onClick={() => setTheme("dark")}
                  className="bg-slate-900 p-2 rounded-xl"
                >
                  <RiMoonFill size={25} color="white" />
                </button>
              </Fade>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
